#!/usr/bin/python3
import sys
import os
from shutil import which
from subprocess import Popen, PIPE
from collections import defaultdict

dmenu_file = "/home/varun/.local/bin/a"

def is_url(string):
    clean = string.strip()
    if ' ' in clean:
        return False
    if len(clean.split(".")) > 1:
        return True
    return False

def url_format(search):
    nomodify = search
    replacements = [(" ", "%20"),
                    ("!","%21"),
                    ("#","%23"),
                    ("$","%24"),
                    ("%","%25"),
                    ("&","%26"),
                    ("'","%27"),
                    ("(","%28"),
                    (")","%29"),
                    ("*","%2A"),
                    ("+","%2B"),
                    (",","%2C"),
                    ("/","%2F"),
                    (":","%3A"),
                    (";","%3B"),
                    ("=","%3D"),
                    ("?","%3F"),
                    ("@", "%40"),
                    ("[","%5B"),
                    ("]", "%5D")]
    for r in replacements:
        nomodify.replace(r[0], r[1])
    return nomodify

def dmenu(list_strings):
    process = Popen(["sh", "-c", 'echo "{}" | dmenu -p "omnibox" -fn "DejaVuSansMono:size=10"'.format("\n".join(list_strings), dmenu_file)], stdout=PIPE)
    exit_code = process.wait()
    comm = process.communicate()
    if exit_code == 1:
        return
    # list_returned = comm[0].decode('utf-8').split('\n')
    # if len(list_returned) < 2:
        # return None
    # last = list_returned[-2].strip()
    return comm[0].decode('utf-8').strip() 
 
def run(command):
    commands = command.split(" ")
    os.execlp(commands[0], commands[0], *commands[1:])
 
def surf(string):
    if is_url(string):
        os.execlp("surf", "surf", "-z", "1.2", "-aA", string)
    else:
        search = "https://duckduckgo.com/{}".format(url_format(string))
        os.execlp("surf", "surf", "-z", "1.2", search)

# GET list of runable programs ######
programs = set()
for path in os.environ["PATH"].split(":"):
    for program in os.listdir(path):
        programs.add(program)
programs = list(programs)
####################################

usin = ""
lines = []

with open("/home/varun/.recent", "r") as f:
    lines = [l.strip().replace("'","") for l in f.readlines()]
    weights = defaultdict(int)
    for l in lines: 
        weights[l] += 1
    sorted_lines = sorted(weights, key=weights.__getitem__)[::-1]
    usin = dmenu(sorted_lines + programs)

# check if a command is actually entered
if not usin or len(usin) == 0:
    sys.exit(0)    
 
with open("/home/varun/.recent", "w") as f:
    f.write(usin + "\n")
    f.write("\n".join(lines[:1000]))

# check first characters
if usin[0] == "?":
    surf(url_format(usin[1:]))
elif usin[0] == "$":
    run(usin[1:])
elif is_url(usin):
    surf(usin)
elif which(usin.split(" ")[0]) is not None:
    run(usin)
else:
    surf(usin)
sys.exit(0)
