#!/bin/bash
if [ $1 = -h ]
then
	echo "us downloads Supreme Court opinions in the U.S. reports from the library of Congress.";
	echo "Usage: us <volume> <page>";
else
curl https://cdn.loc.gov/service/ll/usrep/usrep$1/usrep$1$2/usrep$1$2.pdf > $1us$2.pdf
fi
